# Makefile for Assignment 2

hw2: poj.buildrooms.o
		gcc poj.buildrooms.o -o hw2

poj.buildrooms:
		gcc -g poj.buildrooms.c

#poj.adventure:
#	  gcc -g poj.adventure.c

clean:
	  # For files:
		rm -f *.o *.out

		# For directories:
		rm -rf poj.rooms*

